### ISSUE TITLE
mount.fstab fails

### ISSUE THREAD

**Issue by No9** [fubarnetes/libjail-rs#45]
Hi - Thanks for the library kind of cool that so many freebsd primatives are coming to Rust.
I was testing out building a readonly jail using an fstab definition on my system.

`.param("mount.fstab", param::Value::String("/etc/fstab.rojail".to_string()))`

I got 
```
thread 'main' panicked at 'could not start jail: JailSetError("unknown parameter: mount.fstab")', src/libcore/result.rs:1009:5
``` 

Looking at `jail(8)` I see it's a pseudo-parameter so I wasn't too surprised but thought I would raise this if you start to prioritize them.

**Comment by gronke** [comment]
`mount.fstab` is not a parameter, but feature of the usr.sbin/jail command (see [usr.sbin/jail/command.c](https://github.com/freebsd/freebsd/blob/42ccecb54bc6d2fd91950ba895e4ac88c7a08efd/usr.sbin/jail/command.c#L451-L494)).

**Comment by fabianfreyer** [comment]
Hi! Yeah, for now pseudo-parameters are out of scope, as they're kind of an anti-feature in a setting where you're a downstream consumer of a library and have more flexibility in setting up state there. The scope of `libjail-rs` is really just setting up jail-related kernel state. OTOH - Probably this should be documented somewhere.

A framework to do things around the lifetime of jails is being worked on at https://github.com/fubarnetes/guardian, but that's still in the [specification stages](https://github.com/fubarnetes/guardian/wiki/Spec). I'd be more than happy to hear feeback there!

**Comment by No9** [comment]
@gronke Thanks for the detail on what a "pseudo-parameter" is in this instance.

I really like the idea of guardian - in fact I think it's the type of thing I was looking to build out myself. I'll close this and move the conversation over there.
