### ISSUE TITLE
RCTL/RACCT statistics

### ISSUE THREAD

**Issue by fabianfreyer** [fubarnetes/libjail-rs#8]
Import the `rctl(8)` code from [phyber/jail_exporter](https://github.com/phyber/jail_exporter). I guess the API could be something along the lines of:

```rust
fn RunningJail::resource_usage(&self) -> Result<HashMap<String,i64>,JailError>
```

If `RCTL`/`RACCT` are unavailable or disabled, an appropriate `JailError` should be returned.

**Comment by phyber** [comment]
The `rctl` calls can do more than just give Jail metrics. There's probably scope for a `librctl-rs` there.

**Comment by fabianfreyer** [comment]
Thanks for agreeing to relicense!

Agreed on `librctl-rs`. For now, I'd suggest adding generalized functions here in a `mod rctl`, and then later, once that matured, splitting that module out into a crate. Would that sound reasonable to you, @phyber?

If you'd be up to it, feel free to create a PR. Otherwise, I'd also be happy to do it :)

**Comment by phyber** [comment]
Sounds reasonable. Hopefully I'll have some time this weekend to take a look at this :)

**Comment by fabianfreyer** [comment]
@phyber, would you mind taking a look at #9 ? I believe that should mostly cover your use cases by now - however it would be great to hear if the API / etc. is sufficient for your needs :)
